/* 
 * Copyright (C) 2019 samsul
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package adppdb.view.operator;

import adppdb.controller.DataSekolahController;
import adppdb.database.JDBCAdapter;
import adppdb.model.Operator;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author samsul
 */
public class AturSekolahInternalFrame extends javax.swing.JInternalFrame {

    private final DataSekolahController dA;
    private Operator operator;

    /**
     * Creates new form BerandaInternalFrame
     */
    public AturSekolahInternalFrame(Operator loggedInOperator) {
        initComponents();
        dA = new DataSekolahController(this);
        this.operator = loggedInOperator;

        try {
            PreparedStatement stmt = JDBCAdapter.getConnection()
                    .prepareStatement("SELECT * FROM smp WHERE id = ?");

            stmt.setInt(1, Integer.parseInt(loggedInOperator.getSmp().getId()));

            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                kecamatanView.setText(rs.getString("kecamatan"));
                npsnView.setText(rs.getString("npsn"));

                if (rs.getString("status") == "N") {
                    negeri.setSelected(true);
                } else {
                    swasta.setSelected(true);
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }

        npsnView.setText(loggedInOperator.getSmp().getNpsn());
        namaView.setText(loggedInOperator.getSmp().getNama());

        if (loggedInOperator.getSmp().getStatus() == "N") {
            negeri.setSelected(true);
        } else {
            swasta.setSelected(true);
        }

        batasView.setText(loggedInOperator.getSmp().getBatasPenerimaan());
        alamatView.setText(loggedInOperator.getSmp().getAlamatJalan());
    }

    public Operator getOperator() {
        return operator;
    }

    private void setMinMaxTableColumnWidth(javax.swing.JTable table, int column, int width) {
        table.getColumnModel().getColumn(column).setMinWidth(width);
        table.getColumnModel().getColumn(column).setMaxWidth(width);
    }

    public JTextArea getAlamatView() {
        return alamatView;
    }

    public JTextField getBatasView() {
        return batasView;
    }

    public JTextField getKecamatanView() {
        return kecamatanView;
    }

    public JTextField getNamaView() {
        return namaView;
    }

    public JTextField getNpsnView() {
        return npsnView;
    }

    public JRadioButton getNegeri() {
        return negeri;
    }

    public JRadioButton getSwasta() {
        return swasta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        negeri = new javax.swing.JRadioButton();
        namaView = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        npsnView = new javax.swing.JTextField();
        swasta = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatView = new javax.swing.JTextArea();
        kecamatanView = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        batasView = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        simpanBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(960, 570));
        setPreferredSize(new java.awt.Dimension(960, 570));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Atur Sekolah");
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel2.setText("Nama");

        status.add(negeri);
        negeri.setText("Negeri");

        namaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaViewActionPerformed(evt);
            }
        });

        jLabel4.setText("Status");

        status.add(swasta);
        swasta.setText("Swasta");

        alamatView.setColumns(20);
        alamatView.setRows(2);
        jScrollPane2.setViewportView(alamatView);

        jLabel5.setText("Batas Penerimaan");

        jLabel12.setText("Alamat");

        jLabel10.setText("Kecamatan");

        jLabel3.setText("NPSN");

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(simpanBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(batasView)
                                .addComponent(npsnView, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kecamatanView, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(negeri)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(swasta))
                                .addComponent(jLabel4)))
                        .addComponent(namaView, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(namaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(npsnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kecamatanView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(batasView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(negeri)
                            .addComponent(swasta))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(simpanBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaViewActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        dA.simpanAturSekolah();
    }//GEN-LAST:event_simpanBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatView;
    private javax.swing.JTextField batasView;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kecamatanView;
    private javax.swing.JTextField namaView;
    private javax.swing.JRadioButton negeri;
    private javax.swing.JTextField npsnView;
    private javax.swing.JButton simpanBtn;
    private javax.swing.ButtonGroup status;
    private javax.swing.JRadioButton swasta;
    // End of variables declaration//GEN-END:variables
}
